version: "3.2"
services:
  web:
    build:
      context: ./frontend
    image: alicelukas/web-mysql-app
    networks:
      - frontend
    ports:
      - "80:8006"
    container_name: moe-web-app
    restart: always
  server:
    build:
      context: ./backend
    image: alicelukas/server-mysql-app
    networks:
      - backend
    environment:
      - MYSQL_HOST=moe-mysql-app
      - MYSQL_USER=moeuser
      - MYSQL_PASS=moepass
      - MYSQL_DB=moe_db
    ports:
      - "30001:8005"
    container_name: moe-server-app
    restart: always
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=moeuser
      - MYSQL_PASSWORD=moepass
      - MYSQL_DATABASE=moe_db
    volumes:
      - "./backend/init/:/docker-entrypoint-initdb.d/"
    ports:
      - 3306:3306
    container_name: moe-mysql-app
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=moe-mysql-app
      - PMA_PORT=3306
    volumes:
      - /sessions
    container_name: moe-phpmyadmin-app
    restart: always
networks:
  frontend:
  backend:
